/*
 * GENERATED by scripts/optimise-images.py — do not edit.
 *
 * Maps an image base name to the widths that were actually generated.
 * utils/imageSrc.js consults this so a srcset never advertises a tier
 * that the no-upscale rule skipped.
 */

export const imageManifest = {
  /* no images processed yet */
};
